import localFont from "next/font/local";
import "./globals.css";
import Footer from "./components/global/Footer";
import Navigation from "./components/global/Navigation";

// const inter = Inter({ subsets: ['latin'] })
const rebond = localFont({
  src: [
    {
      path: "./fonts/ESRebondGrotesque-Light.woff2",
      weight: "300",
      style: "light",
    },
    {
      path: "./fonts/ESRebondGrotesque-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/ESRebondGrotesque-Medium.woff2",
      weight: "500",
      style: "medium",
    },
    {
      path: "./fonts/ESRebondGrotesque-Bold.woff2",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-heading",
});

const suisse = localFont({
  src: [
    {
      path: "./fonts/suisseneue-light-webfont.woff2",
      weight: "300",
      style: "light",
    },
    {
      path: "./fonts/suisseneue-medium-webfont.woff2",
      weight: "500",
      style: "medium",
    },
    {
      path: "./fonts/suisseneue-regular-webfont.woff2",
      weight: "400",
      style: "bold",
    },
  ],
  variable: "--font-body",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rebond.variable} ${suisse.variable}`}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
